name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  find-images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.list.outputs.paths }}

    steps:
      - name: Find directories with Dockerfile
        id: list
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "images"

  build:
    name: Build image
    needs: find-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.find-images.outputs.images) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          image_name=$(basename $(dirname ${{ matrix.image }}))
          dir_name=$(dirname ${{ matrix.image }})
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}-$image_name:latest $dir_name --push
