name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  find-dirs:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find directories with Dockerfile
        id: set-dirs
        run: |
          dirs=$(find images -type f -name Dockerfile -exec dirname {} \; | sort | uniq | jq -R . | jq -s .)
          echo "::set-output name=dirs::$dirs"

  build:
    needs: find-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-dirs.outputs.dirs) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          image_name=$(basename ${{ matrix.dir }})
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-$image_name:latest ${{ matrix.dir }} --push
